orgchart/Models/EmployeeUser.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace orgchart.Models
{

    [Table("employee_user")]
    public class EmployeeUser : IBaseModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        public int user_id { get; set; }

        public int employee_id { get; set; }

        public DateTime? created_at { get; set; }

        public DateTime? modified_at { get; set; }

        public int created_by { get; set; }

        public int modified_by { get; set; }
    }
}

orgchart/Models/EmployeeUserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace orgchart.Models
{
    public class EmployeeUserViewModel
    {
        public List<User> VM_USERS { get; set; }
        public User VM_USER { get; set; }
        public List<Employee> VM_EMPLOYEES { get; set; }
        public Employee VM_EMPLOYEE { get; set; }
        public List<Designation> VM_DESIGNATIONS { get; set; }
        public Designation VM_DESIGNATION { get; set; }
        public List<Department> VM_DEPARTMENTS { get; set; }
        public Department VM_DEPARTMENT { get; set; }

        public List<EmployeeUser> VM_EMPLOYEEUSERS { get; set; }
        public EmployeeUser VM_EMPLOYEEUSER { get; set; }
    }
}

orgchart/Controllers/EmployeeController.cs
using orgchart.Models;
using orgchart.SecurityAuth;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace orgchart.Controllers
{
    public class EmployeeController : Controller
    {   /// <summary>
        /// Index page 
        /// for show all employees list
        /// </summary>  
        /// <returns></returns>
        // GET: Employee

        //[SecurityAuthAuthorize(AccessLevels = 
        //    new AccessLevel[] {
        //    AccessLevel.View,
        //    AccessLevel.Create,
        //    AccessLevel.Delete,
        //    AccessLevel.Update })]
        public ActionResult Index()
        {
            //Get Current UserName
            int id = Convert.ToInt32(User.Identity.Name);
            //Current Compamy
            company find_company = new DBContext().companies.ToList().Find(x => x.user_id == id);

            //Set  Message
            String message = "";

            //Check Tempdate error or successmessage 
            if (TempData["message"] != null)
            {
                message = TempData["message"].ToString();
            }

            //view data send message
            ViewData["message"] = message;

            //Find all employees list into a list and bind/pass to view
            List<Employee> lstemployees = new DBContext().employees.ToList().FindAll(x => x.company_id == find_company.id);
            return View(lstemployees);
        }

        /// <summary>
        /// Create Page for Employee 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult create(String id)
        {
            //Get Current UserName
            int user_id = Convert.ToInt32(User.Identity.Name);
            //Current Compamy
            company find_company = new DBContext().companies.ToList().Find(x => x.user_id == user_id);

            //Set  Message
            String message = "";


            int dID = Convert.ToInt32(id);
            

            //pass model to view
            Employee mdlEmployee = new Employee();

            //Check if id doesnot null
            if (id != null && id != "0")
            {
                //check if Employee already exist
                if (new DBContext().employees.ToList().FindAll(x => x.id == dID).Count > 0)
                {
                    //pass model to view with Employee info
                    mdlEmployee = new DBContext().employees.Find(dID);
                }
            }

            //Check Temp error or successmessage 
            if (TempData["message"] != null)
            {
                message = TempData["message"].ToString();
            }


            //view data send message
            ViewData["message"] = message;

            return View(mdlEmployee);
        }

        /// <summary>
        /// Store Desiognation 
        /// Create or Update
        /// </summary>
        /// <param name="EmployeeMdl"></param>
        /// <returns></returns>
        /// 
        [HttpPost]
        public ActionResult store(Employee EmployeeMdl)
        {
            
            //Get Current UserName
            int id = Convert.ToInt32(User.Identity.Name);
            //Current Compamy
            company find_company = new DBContext().companies.ToList().Find(x => x.user_id == id);

            String imgFileLocation = "";

            //Check Model state is valid or not
            if (ModelState.IsValid)
            {
                
                //Check File
                if (Request.Files.Count>0)
                {
                    HttpPostedFileBase file= Request.Files[0];

                    double file_size = Convert.ToDouble(file.ContentLength) / 1000000;

                    //Check fileupload or not
                    if (file.ContentLength > 0)
                    {
                        //Check Upload file length maximum  1MB
                        if (file_size <= 1)
                        {
                            //Check file extension jpg or png only
                            string extension = file.FileName.Split('.')[1];
                            if (extension.Equals("jpg") || extension.Equals("png"))
                            {
                                var file_save_path = "/content/images/uploads";
                                var fileName = Path.GetFileName(file.FileName);
                                string FileExtn = Path.GetExtension(file.FileName);
                                fileName = Guid.NewGuid().ToString().Replace("-", "") + FileExtn;
                                String fileLocation = Path.Combine(Server.MapPath("~/" + file_save_path), fileName);
                                file.SaveAs(fileLocation);
                                imgFileLocation = string.Format("{0}/{1}", file_save_path, fileName);
                            }
                            else
                            {
                                //Set temp data Error message
                                TempData["message"] = Utility.FAILED_MESSAGE + " File Must be .JPG or .PNG format";
                                return RedirectToAction("create", new { id = EmployeeMdl.id });
                            }

                        }
                        else
                        {
                            //Set temp data Error message
                            TempData["message"] = Utility.FAILED_MESSAGE + " Maximum FIle Limit 1MB";
                            return RedirectToAction("create", new { id = EmployeeMdl.id });
                        }
                    }
                }

                //check if already exist then update
                if (new DBContext().employees.ToList().FindAll(x => x.id == EmployeeMdl.id).Count > 0)
                {
                    //Update Employee
                    //EmployeeMdl.updated_at = DateTime.Now;
                    //Set image
                    //Check no image
                    if (imgFileLocation != "")
                    {
                        EmployeeMdl.photo = imgFileLocation;
                    }
                    using (var contxt = new DBContext())
                    {
                        contxt.employees.Attach(EmployeeMdl);
                        contxt.Entry(EmployeeMdl).State = EntityState.Modified;
                        contxt.SaveChanges();

                    }
                    //Set temp data Success registration message
                    TempData["message"] = Utility.SUCCESS_MESSAGE + "Employee Updated successfully";
                }
                else
                {
                    //Add new Employee
                    using (var contxt = new DBContext())
                    {
                        //Set Datetime
                       // EmployeeMdl.created_at = DateTime.Now;
                        //set comapmny id
                        EmployeeMdl.company_id = find_company.id;

                        //Set upload photo path
                        if (imgFileLocation != "")
                        {
                            EmployeeMdl.photo = imgFileLocation;
                        }

                        //Add New Employee
                        contxt.employees.Add(EmployeeMdl);
                        contxt.SaveChanges();

                    }
                    //Set temp data Success registration message
                    TempData["message"] = Utility.SUCCESS_MESSAGE + "Employee Add Successfully";
                }

                return RedirectToAction("index");
            }
            else
            {
                string errors = errorstate.errors(ModelState);
                //Set temp data for wrong credentials
                TempData["message"] = Utility.FAILED_MESSAGE + "" + errors;

                //redirect back to Registration page 
                return RedirectToAction("create", new { id = EmployeeMdl.id });
            }
        }


        public ActionResult delete(String id)
        {
            //Check if  not null
            if (id != null)
            {
                int dID = Convert.ToInt32(id);

                //Find the Employee 
                Employee dgMdl = new DBContext().employees.Find(dID);


                //Delete The Employee
                using (var contxt = new DBContext())
                {
                    contxt.Entry(dgMdl).State = EntityState.Deleted;
                    contxt.SaveChanges();
                }

                //Set temp data Success message
                TempData["message"] = Utility.SUCCESS_MESSAGE + "Employee Deleted Successfully";

            }
            else
            {
                //Set temp data Success registration message
                TempData["message"] = Utility.FAILED_MESSAGE + "Something went wrong";
            }
            return RedirectToAction("index");
        }



        public PartialViewResult employeedetails(String id)
        {
            int eID = Convert.ToInt32(id);
            Employee empMdl = new DBContext().employees.Find(eID);
            return PartialView(empMdl);
        }

    }
}

orgchart/Controllers/EmployeeUserController.cs
using orgchart.Models;
using orgchart.SecurityAuth;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace orgchart.Controllers
{
    public class EmployeeUserController : Controller
    {
        // GET: EmployeeUser
        public ActionResult Index()
        {
            //Get Current UserName
            int id = Convert.ToInt32(User.Identity.Name);
            //Current Compamy
            company find_company = new DBContext().companies.ToList().Find(x => x.user_id == id);

            //Set  Message
            String message = "";

            //Check Tempdate error or successmessage 
            if (TempData["message"] != null)
            {
                message = TempData["message"].ToString();
            }

            //view data send message
            ViewData["message"] = message;

            //Find all employees list into a list and bind/pass to view
            List<Employee> lstEmployeesForUser = new DBContext().employees.ToList().FindAll(x => x.company_id == find_company.id);
            return View(lstEmployeesForUser);
        }

        public ActionResult assign(String empID)
        {
            //Get Current UserName
            int user_id = Convert.ToInt32(User.Identity.Name);
            //Current Compamy
            company find_company = new DBContext().companies.ToList().Find(x => x.user_id == user_id);

            //Set  Message
            String message = "";


            int eID = Convert.ToInt32(empID);


            //pass model to view
            Employee mdlEmployee = new Employee();

            //Check if id doesnot null
            if (empID != null && empID != "0")
            {
                //check if Employee already exist
                if (new DBContext().employees.ToList().FindAll(x => x.id == eID).Count > 0)
                {
                    //pass model to view with Employee info
                    mdlEmployee = new DBContext().employees.Find(eID);
                }
            }

            //Check Temp error or successmessage 
            if (TempData["message"] != null)
            {
                message = TempData["message"].ToString();
            }


            //view data send message
            ViewData["message"] = message;
            EmployeeUserViewModel vm = new EmployeeUserViewModel();
            vm.VM_EMPLOYEE = mdlEmployee;
            vm.VM_USER = new User();
            vm.VM_EMPLOYEEUSER = new EmployeeUser();

            return View(vm);
        }

        public ActionResult store(EmployeeUserViewModel euViewModel)
        {
            //Get Current UserName
            int id = Convert.ToInt32(User.Identity.Name);
            //Current Compamy
            company find_company = new DBContext().companies.ToList().Find(x => x.user_id == id);

            //Check Model state is valid or not
            if (ModelState.IsValid)
            {

                //Check if already exists
                if (new DBContext().employee_users.ToList().FindAll(x => x.employee_id == euViewModel.VM_EMPLOYEEUSER.employee_id).Count > 0)
                {
                    //Delete The EmployeeUser
                    EmployeeUser existingEmployeeUser = new DBContext().employee_users.ToList().Find(x => x.employee_id == euViewModel.VM_EMPLOYEEUSER.employee_id);
                    using (var contxt = new DBContext())
                    {
                        contxt.Entry(existingEmployeeUser).State = EntityState.Deleted;
                        contxt.SaveChanges();
                    }
                }
                //Add new EmployeeUser
                using (var contxt = new DBContext())
                {
                    //Set Datetime
                    //EmployeeMdl.created_at = DateTime.Now;
                    //set comapmny id
                    //euViewModel.VM_EMPLOYEE.company_id = find_company.id;
                    //Add New EmployeeUser
                    EmployeeUser employeeUser = new EmployeeUser
                    {
                        employee_id = euViewModel.VM_EMPLOYEEUSER.employee_id,
                        user_id = euViewModel.VM_EMPLOYEEUSER.user_id
                    };
                    contxt.employee_users.Add(employeeUser);
                    contxt.SaveChanges();

                }
                //Set temp data Success registration message
                TempData["message"] = Utility.SUCCESS_MESSAGE + "Employee Assigned Successfully";

                return RedirectToAction("index");
            }

            else
            {
                string errors = errorstate.errors(ModelState);
                //Set temp data for wrong credentials
                TempData["message"] = Utility.FAILED_MESSAGE + "" + errors;

                String param_id = euViewModel.VM_EMPLOYEEUSER.employee_id.ToString();
                //redirect back to assign page 
                return RedirectToAction("assign", new { empID = param_id });
            }
        }
    }
}

orgchart/Views/EmployeeUser/Index.cshtml
@using orgchart.Models
@model List<Employee>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Employees
        </h1>
    </section>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-xs-12">
                @{
                    String message = ViewData["message"].ToString();

                }
                @if (message != "" && message.StartsWith(Utility.FAILED_MESSAGE))
                {
                    message = message.Replace(Utility.FAILED_MESSAGE, "");
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @Html.Raw(message)
                    </div>
                }
                else if (message != "" && message.StartsWith(Utility.SUCCESS_MESSAGE))
                {
                    message = message.Replace(Utility.SUCCESS_MESSAGE, "");
                    <div class="alert alert-info alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @Html.Raw(message)
                    </div>
                }

                <div class="box">
                    <div class="row">
                        <div class="col-lg-12">

                        </div>

                    </div>

                    <div class="box-header">
                        <h3 class="box-title">List of Employee</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Employee ID</th>
                                    <th>Employee Name</th>
                                    <th>Department</th>
                                    <th>Designation</th>
                                    @*<th>Action</th>*@
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (Employee lst in Model)
                                {
                                    String department_name = "";
                                    String designation_name = "";
                                    if (new DBContext().departments.ToList().FindAll(x => x.id == lst.department_id).Count > 0)
                                    {
                                        department_name = new DBContext().departments.Find(lst.department_id).name;
                                    }

                                    if (new DBContext().designations.ToList().FindAll(x => x.id == lst.designation_id).Count > 0)
                                    {
                                        designation_name = new DBContext().designations.Find(lst.designation_id).name;
                                    }

                                    <tr>
                                        <td>@lst.id</td>
                                        <td>@lst.first_name   @lst.last_name</td>
                                        <td>@department_name</td>
                                        <td>@designation_name</td>

                                        <td>
                                            <a class="btn btn-primary" href="@Url.Action("assign","EmployeeUser",new {empID=lst.id })"><i class="fa fa-fw fa-plus"></i> Assign </a>
                                        </td>
                                    </tr>
                                }
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>

@section masterJs
{

    <script>

        var base_rel= "@Url.Action("delete","Employee")";

  $(function () {
      $('#example2').DataTable({
          'paging': true,
          'lengthChange': true,
          'searching': true,
          'ordering': true,
          'info': true,
          'autoWidth': true
      })
  })

  function remove(obj)
  {
      var r = confirm("Are you Sure ,you want to delete this?");
      if (r == true) {
          window.location.href = base_rel + "?id=" + obj;
      } else {
          txt = "You pressed Cancel!";
      }


  }

    </script>
}

orgchart/Views/EmployeeUser/assign.cshtml
@model orgchart.Models.EmployeeUserViewModel
@using orgchart.Models
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "assign";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    int id = Convert.ToInt32(User.Identity.GetUserName());
    User current_user = new DBContext().users.Find(id);
    String name = current_user.first_name + " " + current_user.last_name;
    company find_company = new DBContext().companies.ToList().Find(x => x.user_id == id);
    List<User> allUsers = new DBContext().users.ToList();
    List<EmployeeUser> allEmployeeUsers = new DBContext().employee_users.ToList();
    Model.VM_DEPARTMENTS = new DBContext().departments.ToList();
    Model.VM_DESIGNATIONS = new DBContext().designations.ToList();
    EmployeeUser existingEmployeeUser = allEmployeeUsers.Find(x => x.employee_id == Model.VM_EMPLOYEE.id);
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Employee
        </h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">

            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">

                    @{
                        String message = ViewData["message"].ToString();

                    }
                    @if (message != "" && message.StartsWith(Utility.FAILED_MESSAGE))
                    {
                        message = message.Replace(Utility.FAILED_MESSAGE, "");
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            @Html.Raw(message)
                        </div>
                    }
                    else if (message != "" && message.StartsWith(Utility.SUCCESS_MESSAGE))
                    {
                        message = message.Replace(Utility.SUCCESS_MESSAGE, "");
                        <div class="alert alert-info alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            @Html.Raw(message)
                        </div>
                    }

                    <!-- /.box-header -->
                    <!-- form start -->

                    <div class="form-group">
                        <label>Employee Name</label>
                        <p> @Model.VM_EMPLOYEE.first_name @Model.VM_EMPLOYEE.last_name </p>
                    </div>

                    <div class="form-group">
                        <label>Department</label>
                        <p> @Model.VM_DEPARTMENTS.Find(x => x.id == Model.VM_EMPLOYEE.department_id).name </p>
                    </div>

                    <div class="form-group">
                        <label>Designation</label>
                        <p> @Model.VM_DESIGNATIONS.Find(x => x.id == Model.VM_EMPLOYEE.designation_id).name </p>
                    </div>

                    
                    @using (Html.BeginForm("Store", HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString(), FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                    <input type="hidden" value="@Model.VM_EMPLOYEE.id" name="VM_EMPLOYEEUSER.employee_id" />
                    <div class="form-group">
                        <label>Select User</label>
                        <select name="VM_EMPLOYEEUSER.user_id" class="form-control">
                            
                            @foreach (User user in allUsers)
                            {
                                if (existingEmployeeUser == null || user.id != existingEmployeeUser.user_id)
                                {
                                    <option value="@user.id">@user.first_name @user.last_name</option>
                                }
                            }
                        </select>
                    </div>
                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Assign</button>
                        </div>
                    }

                </div>

    </section>
    <!-- /.content -->
</div>